#!/usr/bin/env bash
# Decompile one or more addresses of the Digibox application image.
#
# WHY THIS EXISTS. The firmware is mixed MIPS32 and MIPS16 reached through JALX, and reading it
# by hand -- one function at a time, following pool words to their targets -- was the slowest
# part of this reverse engineering. Ghidra's MIPS:BE:32:16e language decodes it correctly (proved
# against the emulator, which executes the same bytes) and its decompiler turns a page of MIPS16
# into readable C.
#
# WHAT IT IS NOT. Ghidra reads the image; the EMULATOR is the ground truth. Every structural
# claim this project has settled came from tracing the machine, and twice the static reading was
# backwards -- the "CRSL" tag test and the halfword id both looked the other way round on the
# page. Use this to read faster, then prove it by running it.
#
# The project is regenerated by ./ctl.sh ghidra:import when it is missing; it lives in ghidra/
# and is gitignored, because an analysis database is not source.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GHIDRA="${GHIDRA_HOME:-/opt/ghidra}"
PROJ="$ROOT/ghidra/proj"

if [ ! -x "$GHIDRA/support/analyzeHeadless" ]; then
  echo "Ghidra not found at $GHIDRA — set GHIDRA_HOME, or install it there." >&2
  exit 2
fi
if [ ! -d "$PROJ/digibox.rep" ]; then
  echo "no Ghidra project yet — run ./ctl.sh ghidra:import first" >&2
  exit 2
fi
if [ $# -eq 0 ]; then
  echo "usage: $0 0x8005141C [0x8008C8A8 …]" >&2
  exit 2
fi

# -readOnly so two of these can run at once without fighting over the project lock, and so a
# decompile can never modify the database it is reading.
"$GHIDRA/support/analyzeHeadless" "$PROJ" digibox \
  -process unpacked_mine.bin -noanalysis -readOnly \
  -scriptPath "$ROOT/ghidra/scripts" -postScript DigiboxDump.java "$@" 2>&1 \
  | sed -n '/====/,$p' \
  | sed -e 's/^INFO  DigiboxDump\.java> //' -e 's/ (GhidraScript)  $//'
