// Code generated by tools/gen-wire.mjs from schema/wire.json; DO NOT EDIT.
package wire

const Version = 1
const FrameWidth = 720
const FrameHeight = 576

type PaletteMessage struct {
	Type    string `json:"type"`
	Version int    `json:"version"`
	Epoch   uint64 `json:"epoch"`
	RGB     []byte `json:"rgb"`
}

type FrameMessage struct {
	Type    string `json:"type"`
	Version int    `json:"version"`
	Seq     uint64 `json:"seq"`
	X       uint32 `json:"x"`
	Y       uint32 `json:"y"`
	W       uint32 `json:"w"`
	H       uint32 `json:"h"`
	Epoch   uint64 `json:"epoch"`
	Pixels  []byte `json:"pixels"`
}

type StateMessage struct {
	Type    string `json:"type"`
	Version int    `json:"version"`
	Phase   string `json:"phase"`
	Reason  string `json:"reason"`
}

type MediaMessage struct {
	Type    string `json:"type"`
	Version int    `json:"version"`
	Active  uint8  `json:"active"`
	Service string `json:"service"`
}

type KeyMessage struct {
	Type    string `json:"type"`
	Version int    `json:"version"`
	Raw     uint8  `json:"raw"`
	Source  uint8  `json:"source"`
}

type ResetMessage struct {
	Type    string `json:"type"`
	Version int    `json:"version"`
}
