import { readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';

const schema = JSON.parse(readFileSync(new URL('../schema/wire.json', import.meta.url), 'utf8'));
const names = Object.keys(schema.messages);
const goType = { uint8: 'uint8', uint32: 'uint32', uint64: 'uint64', string: 'string', base64: '[]byte' };
const tsType = { uint8: 'number', uint32: 'number', uint64: 'number', string: 'string', base64: 'string' };
const title = (value) => value[0].toUpperCase() + value.slice(1);
const go = [
  '// Code generated by tools/gen-wire.mjs from schema/wire.json; DO NOT EDIT.',
  'package wire', '',
  `const Version = ${schema.version}`,
  `const FrameWidth = ${schema.raster.width}`,
  `const FrameHeight = ${schema.raster.height}`, ''
];
const ts = [
  '// Code generated by tools/gen-wire.mjs from schema/wire.json; DO NOT EDIT.',
  `export const WIRE_VERSION = ${schema.version} as const;`,
  `export const FRAME_WIDTH = ${schema.raster.width} as const;`,
  `export const FRAME_HEIGHT = ${schema.raster.height} as const;`, ''
];
for (const name of names) {
  const message = schema.messages[name];
  const typeName = `${title(name)}Message`;
  go.push(`type ${typeName} struct {`, `  Type string \`json:"type"\``, `  Version int \`json:"version"\``);
  ts.push(`export interface ${typeName} {`, `  type: '${name}';`, `  version: typeof WIRE_VERSION;`);
  for (const [field, kind] of Object.entries(message.fields)) {
    const goField = field === 'rgb' ? 'RGB' : title(field);
    const goKind = Array.isArray(kind) ? 'string' : goType[kind];
    const tsKind = Array.isArray(kind) ? kind.map((value) => `'${value}'`).join(' | ') : tsType[kind];
    if (!goKind || !tsKind) throw new Error(`unknown kind ${kind} for ${name}.${field}`);
    go.push(`  ${goField} ${goKind} \`json:"${field}"\``);
    ts.push(`  ${field}: ${tsKind};`);
  }
  go.push('}', '');
  ts.push('}', '');
  for (const [field, kind] of Object.entries(message.fields)) {
    if (Array.isArray(kind)) {
      ts.push(`export const ${name.toUpperCase()}_${field.toUpperCase()}S = ${JSON.stringify(kind)} as const;`, '');
    }
  }
}
for (const direction of ['server', 'client']) {
  const members = names.filter((name) => schema.messages[name].direction === direction).map((name) => `${title(name)}Message`);
  ts.push(`export type ${title(direction)}WireMessage = ${members.join(' | ')};`);
}
ts.push('');
const outputs = [
  [new URL('../internal/wire/wire.go', import.meta.url), execFileSync('gofmt', { input: go.join('\n'), encoding: 'utf8' })],
  [new URL('../web/wire_generated.ts', import.meta.url), ts.join('\n')],
];
for (const [path, content] of outputs) {
  if (process.argv.includes('--check')) {
    if (readFileSync(path, 'utf8') !== content) throw new Error(`${path.pathname} differs from schema/wire.json`);
  } else {
    writeFileSync(path, content);
  }
}
