// Code generated by tools/gen-wire.mjs from schema/wire.json; DO NOT EDIT.
export const WIRE_VERSION = 2 as const;
export const FRAME_WIDTH = 720 as const;
export const FRAME_HEIGHT = 576 as const;

export interface PaletteMessage {
  type: 'palette';
  version: typeof WIRE_VERSION;
  epoch: number;
  rgb: string;
  alpha: string;
}

export interface FrameMessage {
  type: 'frame';
  version: typeof WIRE_VERSION;
  seq: number;
  x: number;
  y: number;
  w: number;
  h: number;
  epoch: number;
  pixels: string;
}

export interface StateMessage {
  type: 'state';
  version: typeof WIRE_VERSION;
  phase: 'booting' | 'flash-check' | 'channel-list' | 'ready' | 'halted';
  reason: string;
}

export const STATE_PHASES = ["booting","flash-check","channel-list","ready","halted"] as const;

export interface MediaMessage {
  type: 'media';
  version: typeof WIRE_VERSION;
  active: number;
  service: string;
}

export interface KeyMessage {
  type: 'key';
  version: typeof WIRE_VERSION;
  raw: number;
  source: number;
}

export interface ResetMessage {
  type: 'reset';
  version: typeof WIRE_VERSION;
}

export type ServerWireMessage = PaletteMessage | FrameMessage | StateMessage | MediaMessage;
export type ClientWireMessage = KeyMessage | ResetMessage;
